version: "3.9"
services:
  juno:
    image: local/jupyternotebook:latest
    container_name: jupyternotebook
    command: /miniconda/envs/juno/bin/jupyter notebook --allow-root --port=8888 --ip 0.0.0.0 --no-browser
    # command: /bin/sh -c "while sleep 1000; do :; done" # keep container open while running
    # command: bash
    # stdin_open: true
    # tty: true
    ports: # Host:Container
      - "8888:8888" # Jupyter Notebook
    volumes:
      - type: bind
        source: ./notebooks
        target: /notebooks
      - type: bind
        source: ./
        target: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  juno: