channels:
  - defaults
  - pytorch
  - nvidia # only for cuda
  - conda-forge # tensorflow
dependencies:
  - cudatoolkit #>=11.7 # tensorflow
  - cudnn #>=8.1.0 # tensorflow
  - ipykernel # vscode
  - ipython # vscode
  - notebook
  - pandas # vscode
  - python #>=3.9 # >=3.10 introduces problems with libgcc-ng deps
  - pytorch-cuda #=11.7
  - torchaudio
  - torchvision
  #- libgcc-ng #>=11.2.0 # pytorch
  - pip
  - pip: # add if you'd like to install packages in pip
    - tensorflow # install latest version via pip